openapi: 3.0.0
info:
  version: 2.0.0
  title: G-Links
  description: 'Documentation of the G-Links gene centric data aggregation service. Learn more about [G-Links](http://link.g-language.org/).'
  termsOfService: http://link.g-language.org
  contact:
    name: Kotone Itaya
    email: kotone@sfc.keio.ac.jp
    x-role: responsible developer
servers:
  - url: 'http://link.g-language.org/v2'
    description: 'Development server'
paths:
  '/{query}':
    get:
      summary: 'Aggregate information for given ID'
      parameters:
        - name: query
          in: path
          description: 'Any ID that can be converted to UniProt (see the [input list](http://link.g-language.org/input_list))'
          required: true
          x-valueType:
            - 'http://identifiers.org/agd'
            - 'http://identifiers.org/arachnoserver'
            - 'http://identifiers.org/biocyc'
            - 'http://identifiers.org/cgd'
            - 'http://identifiers.org/conoserver'
            - 'http://identifiers.org/cygd'
            - 'http://identifiers.org/dictybase.gene'
            - 'http://identifiers.org/dip'
            - 'http://identifiers.org/disprot'
            - 'http://identifiers.org/drugbank'
            - 'http://identifiers.org/echobase'
            - 'http://identifiers.org/ecogene'
            - 'http://identifiers.org/eggnog'
            - 'http://identifiers.org/ena.embl'
            - 'http://identifiers.org/ensembl'
            - 'http://identifiers.org/hcvdb'
            - 'http://identifiers.org/flybase'
            - 'http://identifiers.org/genecards'
            - 'http://identifiers.org/genefarm'
            - 'http://identifiers.org/ncbigi'
            - 'http://identifiers.org/hinv.protein'
            - 'http://identifiers.org/hgnc'
            - 'http://identifiers.org/hogenom'
            - 'http://identifiers.org/hovergen'
            - 'http://identifiers.org/hpa'
            - 'http://identifiers.org/hssp'
            - 'http://identifiers.org/ipi'
            - 'http://identifiers.org/kegg'
            - 'http://identifiers.org/maizegdb.locus'
            - 'http://identifiers.org/merops'
            - 'http://identifiers.org/mig'
            - 'http://identifiers.org/omim'
            - 'http://identifiers.org/mint'
            - 'http://identifiers.org/ncbi'
            - 'http://identifiers.org/oma.protein'
            - 'http://identifiers.org/orphanet'
            - 'http://identifiers.org/orthodb'
            - 'http://identifiers.org/pdb'
            - 'http://identifiers.org/peroxibase'
            - 'http://identifiers.org/pharmgkb.gene'
            - 'http://identifiers.org/protclsutdb'
            - 'http://identifiers.org/reactome'
            - 'http://identifiers.org/rebase'
            - 'http://identifiers.org/refseq'
            - 'http://identifiers.org/rgd'
            - 'http://identifiers.org/sgd'
            - 'http://identifiers.org/tair.gene'
            - 'http://identifiers.org/tcdb'
            - 'http://identifiers.org/unigene'
            - 'http://identifiers.org/uniparc'
            - 'http://identifiers.org/vectorbase'
            - 'http://identifiers.org/wormbase'
            - 'http://identifiers.org/xenbase'
            - 'http://identifiers.org/zfin'
            - 'http://identifiers.org/uniprot'
      responses:
        '200':
          description: 'A G-Links response object'
          x-responseValueType:
            - path: uniprot
              valueType: 'http://identifiers.org/uniprot'
            - path: results.id
              valueType:
                - 'http://identifiers.org/agd'
                - 'http://identifiers.org/arachnoserver'
                - 'http://identifiers.org/biocyc'
                - 'http://identifiers.org/cgd'
                - 'http://identifiers.org/conoserver'
                - 'http://identifiers.org/cygd'
                - 'http://identifiers.org/dictybase.gene'
                - 'http://identifiers.org/dip'
                - 'http://identifiers.org/disprot'
                - 'http://identifiers.org/drugbank'
                - 'http://identifiers.org/echobase'
                - 'http://identifiers.org/ecogene'
                - 'http://identifiers.org/eggnog'
                - 'http://identifiers.org/ena.embl'
                - 'http://identifiers.org/ensembl'
                - 'http://identifiers.org/hcvdb'
                - 'http://identifiers.org/flybase'
                - 'http://identifiers.org/genecards'
                - 'http://identifiers.org/genefarm'
                - 'http://identifiers.org/ncbigi'
                - 'http://identifiers.org/hinv.protein'
                - 'http://identifiers.org/hgnc'
                - 'http://identifiers.org/hogenom'
                - 'http://identifiers.org/hovergen'
                - 'http://identifiers.org/hpa'
                - 'http://identifiers.org/hssp'
                - 'http://identifiers.org/ipi'
                - 'http://identifiers.org/kegg'
                - 'http://identifiers.org/maizegdb.locus'
                - 'http://identifiers.org/merops'
                - 'http://identifiers.org/mig'
                - 'http://identifiers.org/omim'
                - 'http://identifiers.org/mint'
                - 'http://identifiers.org/ncbi'
                - 'http://identifiers.org/oma.protein'
                - 'http://identifiers.org/orphanet'
                - 'http://identifiers.org/orthodb'
                - 'http://identifiers.org/pdb'
                - 'http://identifiers.org/peroxibase'
                - 'http://identifiers.org/pharmgkb.gene'
                - 'http://identifiers.org/protclsutdb'
                - 'http://identifiers.org/reactome'
                - 'http://identifiers.org/rebase'
                - 'http://identifiers.org/refseq'
                - 'http://identifiers.org/rgd'
                - 'http://identifiers.org/sgd'
                - 'http://identifiers.org/tair.gene'
                - 'http://identifiers.org/tcdb'
                - 'http://identifiers.org/unigene'
                - 'http://identifiers.org/uniparc'
                - 'http://identifiers.org/vectorbase'
                - 'http://identifiers.org/wormbase'
                - 'http://identifiers.org/xenbase'
                - 'http://identifiers.org/zfin'
                - 'http://identifiers.org/uniprot'
